version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: kigali_crafts_db
    environment:
      MYSQL_ROOT_PASSWORD: oliga123
      MYSQL_DATABASE: kigali_crafts
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-poliga123"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: kigali_crafts_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: kigali_crafts
      DB_USER: root
      DB_PASSWORD: oliga123
      PORT: 5000
      JWT_SECRET: kigalicraftssecret123
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: kigali_crafts_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  mysql_data: